### ISSUE TITLE
Cholette benchmarking not meeting constraint

### ISSUE THREAD

**Issue by jennie-davies** [nbbrd/jdemetra-benchmarking#7]
I have been benchmarking the attached series (Path.txt) to the constraint (Benchmarks.txt) using the Cholette method with rho = 1, lambda = 1 and type = sum. The resulting series is all negative and does not meet the constraints. The series starts in 1999 and the benchmarks start in 2008 so there are unmatched periods. There is a difference in the levels of the series so there is bias that (I think) might not be properly accounted for.
[Benchmarks.txt](https://github.com/nbbrd/jdemetra-benchmarking/files/217354/Benchmarks.txt)
[Path.txt](https://github.com/nbbrd/jdemetra-benchmarking/files/217355/Path.txt)

**Comment by palatej** [comment]
The current implementation supposes that the high-frequency series starts at the beginning of a period of the low-frequency series (for instance, your monthly series should starts in January, which is not the case). We will relax that (too) strong constraint in the next release.

**Comment by jennie-davies** [comment]
Thanks for your very quick response and explanation.
